name: cinemax
description: "Cinemax for movies application "
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  get: ^4.6.6
  firebase_core: ^2.25.4
  flutter_native_splash: ^2.3.10
  http: ^1.2.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  flutter_bloc: ^8.1.3
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.2.2
  cuberto_bottom_bar: ^3.0.0
  equatable: ^2.0.5
  provider: ^6.1.1

flutter_native_splash:
  android: true
  ios : true
  web : false
  image: assets/images/Cinemax_Logo.png
  color: "#1F1D2B"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

# the assets should contain the folder not each file
  assets:
    - assets/images/
  