// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgeWTNRzRIiMk3HYtG5527DsmfEZF3mTc',
    appId: '1:1067870662390:web:c2e9d25aaaed8f3911c6d7',
    messagingSenderId: '1067870662390',
    projectId: 'cinemax-c4269',
    authDomain: 'cinemax-c4269.firebaseapp.com',
    storageBucket: 'cinemax-c4269.appspot.com',
    measurementId: 'G-NE8YSGXPFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3MWE26AC7plWMZXw_8NYR9xuHpYwTJRk',
    appId: '1:1067870662390:android:ba07c2c632f4c51d11c6d7',
    messagingSenderId: '1067870662390',
    projectId: 'cinemax-c4269',
    storageBucket: 'cinemax-c4269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGt2Myk7yaCyRHBd42t2iML3rxbTucPC4',
    appId: '1:1067870662390:ios:9e511ebb0a72d47311c6d7',
    messagingSenderId: '1067870662390',
    projectId: 'cinemax-c4269',
    storageBucket: 'cinemax-c4269.appspot.com',
    iosBundleId: 'com.example.cinemax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGt2Myk7yaCyRHBd42t2iML3rxbTucPC4',
    appId: '1:1067870662390:ios:815a5b4bcabaa9d211c6d7',
    messagingSenderId: '1067870662390',
    projectId: 'cinemax-c4269',
    storageBucket: 'cinemax-c4269.appspot.com',
    iosBundleId: 'com.example.cinemax.RunnerTests',
  );
}
